server:
  port: ${PORT:8080}

spring:
  application:
    name: kinomania-back

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

kinopoisk:
  api:
    url: ${KINOPOISK_API_URL:}
    key: ${KINOPOISK_API_KEY:}

logging:
  level:
    org:
      springframework:
        security: TRACE
